### ISSUE TITLE
Display timestamp for data source displayed in a map

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/shipshape#2]
**Requirement:**

There is a timestamp here indicating the last time the data source for a map was successfully updated/processed.

https://dev.data.solidarityeconomy.coop/dotcoop/meta.json

Add a column entitled _data timestamp_ to Shipshape to display this timestamp.

** Acceptance Criteria **
Look here https://dev-1.solidarityeconomy.coop/shipshape/

Is there a new column for the data timestamps 

Is the timestamp for [mersey-green](https://dev.data.solidarityeconomy.coop/sea-lod/newbridge/meta.json) no more than 10 minutes old?

**Comment by wu-lee** [comment]
This has been implemented and deployed on dev-1. 

You should see a "dataset deployed at" field with a timestamp, which is linked to the `meta.json` file supplying the timestamp (and other data).

Currently this only displays the first dataset's timestamp, pending implementing the facility for shipshape able to display multiple datasets.
